# Generated by Django 3.1.7 on 2021-05-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.IntegerField(default=0)),
                ('subject', models.CharField(blank=True, max_length=4096)),
                ('email_from', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('email_date', models.DateTimeField(blank=True, db_index=True)),
                ('email_body_text', models.TextField(blank=True, max_length=40960)),
                ('email_body_html', models.TextField(blank=True, max_length=40960)),
                ('category', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'db_table': 'email_scrape',
                'ordering': ['email_date'],
            },
        ),
    ]
