# Generated by Django 3.1.7 on 2021-04-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_scrape', '0002_auto_20210405_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='category',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
