# Generated by Django 3.1.7 on 2021-03-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128)),
                ('rating', models.FloatField()),
                ('weight_score', models.FloatField(db_index=True)),
                ('text', models.CharField(max_length=10240)),
                ('review_count', models.IntegerField(blank=True, default=0)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('category', models.CharField(blank=True, max_length=45)),
                ('country', models.CharField(blank=True, max_length=45)),
                ('state', models.CharField(blank=True, max_length=45)),
                ('created_date', models.DateField(blank=True, db_index=True, null=True)),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_review', to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['created_date'],
            },
        ),
    ]
