# Generated by Django 3.1.7 on 2021-03-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128)),
                ('rating', models.FloatField()),
                ('weight_score', models.FloatField()),
                ('text', models.CharField(max_length=2048)),
                ('restaurant_id', models.IntegerField()),
                ('review_count', models.IntegerField()),
                ('category', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('timestamp', models.DateField()),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['timestamp'],
            },
        ),
    ]
