# Generated by Django 3.1.7 on 2021-03-02 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20210302_0405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_date']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='timestamp',
            new_name='created_date',
        ),
    ]
