# Generated by Django 3.1.7 on 2021-03-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20210313_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
