# Generated by Django 3.1.7 on 2021-03-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20210302_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=4096),
        ),
    ]
