# Generated by Django 3.1.7 on 2021-03-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20210315_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.IntegerField(db_index=True, default=0)),
                ('accuracey', models.IntegerField(default=0)),
                ('final_score', models.FloatField(default=0.0)),
                ('duration', models.DateField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'scores_month',
                'ordering': ['final_score'],
            },
        ),
        migrations.CreateModel(
            name='ScoreQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.IntegerField(db_index=True, default=0)),
                ('accuracey', models.IntegerField(default=0)),
                ('final_score', models.FloatField(default=0.0)),
                ('duration', models.DateField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'scores_quarter',
                'ordering': ['final_score'],
            },
        ),
        migrations.CreateModel(
            name='ScoreYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.IntegerField(db_index=True, default=0)),
                ('accuracey', models.IntegerField(default=0)),
                ('final_score', models.FloatField(default=0.0)),
                ('duration', models.DateField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'scores_year',
                'ordering': ['final_score'],
            },
        ),
    ]
