# Generated by Django 3.1.7 on 2021-03-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_scoremonth_scorequarter_scoreyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoremonth',
            old_name='duration',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='scorequarter',
            old_name='duration',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='scoreyear',
            old_name='duration',
            new_name='period',
        ),
        migrations.AddField(
            model_name='scoremonth',
            name='period_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorequarter',
            name='period_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoreyear',
            name='period_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
