# Generated by Django 3.1.7 on 2021-03-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20210302_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
