# Generated by Django 3.1.7 on 2021-03-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20210317_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoremonth',
            name='period_type',
        ),
        migrations.RemoveField(
            model_name='scorequarter',
            name='period_type',
        ),
        migrations.RemoveField(
            model_name='scoreyear',
            name='period_type',
        ),
        migrations.AddField(
            model_name='scoremonth',
            name='review_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='scoremonth',
            name='weight_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scorequarter',
            name='review_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='scorequarter',
            name='weight_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scoreyear',
            name='review_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='scoreyear',
            name='weight_score',
            field=models.FloatField(default=0.0),
        ),
    ]
