# Generated by Django 3.1.7 on 2021-04-29 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210429_0745'),
        ('review', '0008_auto_20210318_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeReviewStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('error_msg', models.CharField(blank=True, default='', max_length=1024)),
                ('scrape_url', models.CharField(blank=True, default='', max_length=256)),
                ('retry_count', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='UNKNOW', max_length=32)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_platform', to='restaurant.platform')),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_scrape', to='restaurant.restaurant')),
            ],
        ),
    ]
