# Generated by Django 3.1.7 on 2021-04-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_scrapereviewstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapereviewstatus',
            options={'ordering': ['res_id']},
        ),
        migrations.AlterModelTable(
            name='scrapereviewstatus',
            table='scrape_status',
        ),
    ]
