# Generated by Django 3.1.7 on 2021-05-01 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20210501_1620'),
        ('review', '0010_auto_20210429_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='res_id',
            field=models.ForeignKey(help_text='Name of the restaurant', on_delete=django.db.models.deletion.CASCADE, related_name='res_review', to='restaurant.restaurant'),
        ),
    ]
