# Generated by Django 3.1.7 on 2021-05-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_auto_20210501_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapereviewstatus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
