# Generated by Django 3.1.7 on 2021-05-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_auto_20210504_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapereviewstatus',
            name='platform',
            field=models.CharField(db_index=True, default='UNKNOW', max_length=32),
        ),
    ]
