# Generated by Django 3.1.7 on 2021-05-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'db_table': 'platform',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.IntegerField(db_index=True, default=0, unique=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('address', models.CharField(blank=True, max_length=1024)),
                ('facebook', models.CharField(blank=True, max_length=1024)),
                ('number_review', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'restaurant',
                'ordering': ['res_id'],
            },
        ),
    ]
