# Generated by Django 3.1.7 on 2021-03-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.IntegerField(db_index=True, default=0)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('number_review', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'restaurant',
                'ordering': ['res_id'],
            },
        ),
    ]
