# Generated by Django 3.1.7 on 2021-06-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_description', models.TextField(blank=True, default='', null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='company email')),
                ('company_website', models.URLField(blank=True, null=True, verbose_name='company website')),
            ],
        ),
    ]
