# Generated by Django 3.1.7 on 2021-06-22 06:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.IntegerField(default=0)),
                ('accessibility', models.IntegerField(default=0)),
                ('best_practices', models.IntegerField(default=0)),
                ('seo', models.IntegerField(default=0)),
                ('first_contentful_paint', models.FloatField(default=0.0)),
                ('speed_index', models.FloatField(default=0.0)),
                ('largest_contentful_paint', models.FloatField(default=0.0)),
                ('interactive', models.FloatField(default=0.0)),
                ('total_blocking_time', models.FloatField(default=0.0)),
                ('cumulative_layout_shift', models.FloatField(default=0.0)),
                ('last_updated_at', models.DateTimeField(default=datetime.date(1970, 1, 1))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_website', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'website_benchmark',
            },
        ),
    ]
