# Generated by Django 3.1.7 on 2021-05-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210429_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['id']},
        ),
    ]
