# Generated by Django 3.1.7 on 2021-05-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20210501_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='res_id',
            field=models.IntegerField(db_index=True, default=0, unique=True),
        ),
    ]
