# Generated by Django 3.1.7 on 2021-06-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_websiteperformance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteperformance',
            name='user',
        ),
        migrations.AddField(
            model_name='websiteperformance',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
