# Generated by Django 3.1.7 on 2021-06-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20210622_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteperformance',
            name='company_website',
            field=models.URLField(blank=True, null=True, verbose_name='company website'),
        ),
    ]
