# Generated by Django 3.1.7 on 2021-05-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeReviewStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_msg', models.CharField(blank=True, default='', max_length=1024)),
                ('res_id', models.IntegerField(default=0)),
                ('scrape_url', models.CharField(blank=True, default='', max_length=512)),
                ('retry_count', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('status', models.CharField(db_index=True, default='UNKNOW', max_length=32)),
                ('platform', models.CharField(db_index=True, default='UNKNOW', max_length=32)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scrape_status',
                'ordering': ['res_id'],
            },
        ),
    ]
