# Generated by Django 3.1.7 on 2021-05-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapereviewstatus',
            name='error_msg',
            field=models.CharField(default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='scrapereviewstatus',
            name='platform',
            field=models.CharField(db_index=True, default='UNKNOW', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='scrapereviewstatus',
            name='retry_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scrapereviewstatus',
            name='review_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scrapereviewstatus',
            name='scrape_url',
            field=models.CharField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='scrapereviewstatus',
            name='status',
            field=models.CharField(db_index=True, default='UNKNOW', max_length=32, null=True),
        ),
    ]
