# Generated by Django 3.1.7 on 2021-05-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_status', '0002_auto_20210519_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapereviewstatus',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scrapereviewstatus',
            name='last_updated_at',
            field=models.DateTimeField(),
        ),
    ]
