# Generated by Django 3.1.7 on 2021-06-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_status', '0003_auto_20210519_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapereviewstatus',
            name='error_msg',
            field=models.CharField(default='', max_length=5000, null=True),
        ),
    ]
